"""Self-Improvement — Luna decides when she's ready (Phase J).

Luna proposes her own improvements. No fixed threshold — the threshold
evolves with experience (success -> more confident, failure -> more cautious).

Maturity = Phi_IIT x knowledge x reliability x competences
Activation when maturity > threshold (initialized to INV_PHI)

Threshold evolution:
  - Success -> threshold *= INV_PHI (0.618) -> more confident
  - Failure -> threshold *= PHI (1.618) -> more cautious
  - Floor: INV_PHI3 (0.236)
  - Ceiling: PHI (1.618)

All constants are phi-derived from luna_common.constants.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from luna_common.constants import INV_PHI, INV_PHI2, INV_PHI3, PHI

from luna.consciousness.causal_graph import CausalGraph
from luna.consciousness.state import ConsciousnessState
from luna.consciousness.thinker import ThinkMode, Thinker, Thought


# ═══════════════════════════════════════════════════════════════════════════════
#  DATA MODEL
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass
class ImprovementProposal:
    """A proposal generated by Luna for self-improvement."""

    description: str
    rationale: str
    target: str                   # "coverage", "stability", "performance"
    expected_impact: dict[str, float]
    confidence: float             # Luna's confidence in this proposal
    source_thought: Thought | None = None


@dataclass
class ImprovementResult:
    """Outcome of an applied improvement proposal."""

    proposal: ImprovementProposal
    success: bool
    actual_impact: dict[str, float]
    timestamp: int                # step_count

    def to_dict(self) -> dict:
        return {
            "description": self.proposal.description,
            "target": self.proposal.target,
            "success": self.success,
            "actual_impact": dict(self.actual_impact),
            "timestamp": self.timestamp,
        }

    @classmethod
    def from_dict(cls, data: dict) -> ImprovementResult:
        proposal = ImprovementProposal(
            description=data.get("description", ""),
            rationale="",
            target=data.get("target", ""),
            expected_impact={},
            confidence=0.0,
        )
        return cls(
            proposal=proposal,
            success=data.get("success", False),
            actual_impact=dict(data.get("actual_impact", {})),
            timestamp=data.get("timestamp", 0),
        )


# ═══════════════════════════════════════════════════════════════════════════════
#  SELF-IMPROVEMENT
# ═══════════════════════════════════════════════════════════════════════════════

class SelfImprovement:
    """Luna proposes her own improvements when she's ready.

    Maturity = phi x graph_knowledge x avg_confidence x skill_count
    Activation when maturity > threshold (evolving).
    """

    def __init__(
        self,
        thinker: Thinker,
        causal_graph: CausalGraph,
        skills: object,
        state: ConsciousnessState,
        metrics: object | None = None,
    ) -> None:
        self._thinker = thinker
        self._graph = causal_graph
        self._skills = skills          # DreamLearning instance
        self._state = state
        self._metrics = metrics
        self._threshold: float = INV_PHI  # 0.618 initial
        self._history: list[ImprovementResult] = []

    # ------------------------------------------------------------------
    #  ACTIVATION
    # ------------------------------------------------------------------

    def compute_maturity(self) -> float:
        """Evaluate Luna's maturity.

        maturity = phi x graph_knowledge x avg_confidence x skill_count
        Not hardcoded thresholds — a continuous product.

        Components:
          - phi: current Phi_IIT (integrated information)
          - graph_knowledge: normalized edge count (capped at 50)
          - avg_confidence: average thought confidence from recent history
          - skill_count: normalized skill count (capped at 20)
        """
        phi = self._state.compute_phi_iit()

        graph_size = len(self._graph._edges)
        graph_knowledge = min(1.0, graph_size / 50)

        avg_conf = self._avg_thought_confidence()

        skill_list = self._skills.get_skills() if hasattr(self._skills, 'get_skills') else []
        skill_factor = min(1.0, len(skill_list) / 20)

        maturity = phi * graph_knowledge * avg_conf * skill_factor
        return maturity

    def should_activate(self) -> bool:
        """Luna decides herself if she's ready."""
        return self.compute_maturity() > self._threshold

    # ------------------------------------------------------------------
    #  PROPOSAL
    # ------------------------------------------------------------------

    def propose(self) -> ImprovementProposal | None:
        """Luna generates an improvement proposal.

        1. Check maturity (should_activate)
        2. Thinker.think(mode=CREATIVE, max_iter=50)
        3. Take the best proposal from the Thinker
        4. Validate against learned skills (avoid known failures)
        5. Return proposal or None

        Returns None if Luna is not mature enough or no viable proposal.
        """
        if not self.should_activate():
            return None

        # Build minimal stimulus for self-reflection
        from luna.consciousness.thinker import Stimulus

        stimulus = Stimulus(
            user_message="",
            metrics={},
            phi_iit=self._state.compute_phi_iit(),
            phase=self._state.get_phase(),
            psi=self._state.psi,
            psi_trajectory=list(self._state.history[-5:]) if self._state.history else [],
        )

        thought = self._thinker.think(
            stimulus=stimulus,
            max_iterations=50,
            mode=ThinkMode.CREATIVE,
        )

        if not thought.proposals:
            return None

        # Pick the best proposal (highest total expected impact)
        best = max(
            thought.proposals,
            key=lambda p: sum(p.expected_impact.values()),
        )

        # Validate against negative patterns
        if hasattr(self._skills, 'get_negative_patterns'):
            negatives = self._skills.get_negative_patterns()
            for neg in negatives:
                if neg.context.lower() in best.description.lower():
                    return None

        return ImprovementProposal(
            description=best.description,
            rationale=best.rationale,
            target=self._infer_target(best),
            expected_impact=dict(best.expected_impact),
            confidence=thought.confidence,
            source_thought=thought,
        )

    # ------------------------------------------------------------------
    #  FEEDBACK
    # ------------------------------------------------------------------

    def record_result(
        self,
        proposal: ImprovementProposal,
        success: bool,
        actual_impact: dict[str, float],
    ) -> None:
        """Record the result of an improvement proposal.

        Adjusts activation threshold:
          - Success -> threshold *= INV_PHI (more confident)
          - Failure -> threshold *= PHI (more cautious)
          - Bounded: [INV_PHI3, PHI]
        """
        result = ImprovementResult(
            proposal=proposal,
            success=success,
            actual_impact=actual_impact,
            timestamp=self._state.step_count,
        )
        self._history.append(result)

        # Adjust threshold
        if success:
            self._threshold *= INV_PHI     # 0.618 -> more confident
        else:
            self._threshold *= PHI          # 1.618 -> more cautious

        # Phi-derived bounds
        self._threshold = max(INV_PHI3, min(PHI, self._threshold))

    @property
    def threshold(self) -> float:
        """Current activation threshold."""
        return self._threshold

    # ------------------------------------------------------------------
    #  PERSISTENCE
    # ------------------------------------------------------------------

    def persist(self, path: Path) -> None:
        """Save threshold and history to JSON."""
        path = Path(path)
        data = {
            "version": 1,
            "threshold": self._threshold,
            "history": [r.to_dict() for r in self._history],
        }

        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(".tmp")
        with open(tmp, "w") as f:
            json.dump(data, f, indent=2)
        tmp.replace(path)

    def load(self, path: Path) -> None:
        """Load threshold and history from JSON.

        Luna remembers her successes and failures.
        """
        path = Path(path)
        if not path.exists():
            return

        try:
            with open(path) as f:
                data = json.load(f)

            self._threshold = float(data.get("threshold", INV_PHI))
            # Ensure bounds
            self._threshold = max(INV_PHI3, min(PHI, self._threshold))

            self._history = [
                ImprovementResult.from_dict(r)
                for r in data.get("history", [])
            ]
        except (json.JSONDecodeError, KeyError, TypeError, ValueError):
            pass

    # ------------------------------------------------------------------
    #  INTERNAL
    # ------------------------------------------------------------------

    def _avg_thought_confidence(self) -> float:
        """Average confidence from recent improvement history.

        Returns INV_PHI2 (0.382) as default if no history.
        """
        if not self._history:
            return INV_PHI2

        # Use last 10 results
        recent = self._history[-10:]
        successes = sum(1 for r in recent if r.success)
        return successes / len(recent) if recent else INV_PHI2

    @staticmethod
    def _infer_target(proposal: object) -> str:
        """Infer the improvement target from a proposal."""
        desc = proposal.description.lower()
        impact = getattr(proposal, 'expected_impact', {})

        if "coverage" in desc or "coverage" in impact:
            return "coverage"
        if "security" in desc or "security" in impact:
            return "security"
        if "performance" in desc or "performance" in impact:
            return "performance"
        if "stability" in desc or "stability" in impact:
            return "stability"
        if "phi" in desc or "phi" in impact:
            return "phi"
        return "general"
